name: Build and test ccronexpr
on:
  push:
    branches:
      - master
    tags:
      - test
      - '[0-9]+.[0-9]+.[0-9]'
  pull_request:
    types: [opened, synchronize, labeled, reopened]
  workflow_dispatch:

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Make build dir
        run: mkdir -p "${{ github.workspace }}/build"
      - name: Build with CMAKE
        run: |
          cmake .
          cmake --build "${{ github.workspace }}/build" --target ccronexpr
      - name: Run test executable
        run: "${{ github.workspace }}/build/ccronexpr"
